import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { DetailSection, FactGrid } from "@/components/detail-section";
import { AlertCard } from "@/components/alert-card";
import { getStoreResult } from "@/lib/data/store";
import { detectAlerts } from "@/lib/domain/alerts";
import { DEFAULT_THRESHOLDS } from "@/lib/domain/config";
import { ageLabel, formatDateTime, formatMoney, hoursBetween } from "@/lib/domain/format";

export const dynamic = "force-dynamic";
export default async function OrderPage({params}:{params:Promise<{id:string}>}){const[result,{id}]=await Promise.all([getStoreResult(),params]);const s=result.snapshot;const order=s.orders.find(item=>item.id===id);if(!order)notFound();const alerts=detectAlerts(s,DEFAULT_THRESHOLDS).filter(alert=>alert.recordId===id||alert.supportingData.some(item=>item.recordId===id));const age=hoursBetween(s.generatedAt,order.createdAt);return <AppShell source={s.source} storeName={s.shop.name} warning={result.liveError}><main className="mx-auto max-w-[980px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><Link href="/orders" className="inline-flex items-center gap-2 text-[9px] font-bold text-[#68736b]"><ArrowLeft size={12}/>All orders</Link><p className="small-caps mt-6 text-[8px] font-bold text-[#828c84]">Source record</p><h1 className="mt-2 text-[34px] font-bold tracking-[-.05em]">Order {order.name}</h1><p className="mt-2 text-[11px] text-[#6b756e]">Created {formatDateTime(order.createdAt,s.shop.timezone)} · {ageLabel(age)} ago</p><div className="mt-6 space-y-4"><DetailSection eyebrow="Order facts" title="Current record"><FactGrid facts={[{label:"Customer",value:order.customerName},{label:"Order value",value:formatMoney(order.total.amount,order.total.currencyCode)},{label:"Fulfilment",value:order.fulfillmentStatus.replaceAll("_"," ")},{label:"Financial status",value:order.financialStatus.replaceAll("_"," ")}]}/></DetailSection><DetailSection eyebrow="Line items" title="Items in this order"><div className="space-y-2">{order.lineItems.map(item=><div key={item.id} className="flex items-center justify-between rounded-xl border border-[#e2e5df] bg-white p-3"><div><p className="text-[10px] font-bold">{item.title}</p><p className="mt-0.5 text-[8px] text-[#858e87]">{item.variantTitle} · Quantity {item.quantity}</p></div><p className="text-[10px] font-bold">{formatMoney(item.total.amount,item.total.currencyCode)}</p></div>)}</div></DetailSection>{alerts.length>0&&<section><p className="small-caps mb-3 text-[8px] font-bold text-[#828c84]">Related findings</p><div className="grid gap-3 sm:grid-cols-2">{alerts.map(alert=><AlertCard key={alert.id} alert={alert}/>)}</div></section>}</div></main></AppShell>}
