import { describe, expect, it } from "vitest";
import { createDemoSnapshot } from "@/lib/demo/seed";
import { DEFAULT_THRESHOLDS } from "@/lib/domain/config";
import { calculateMerchantBacklogs, calculateMetrics, calculateOrderPriority, getOpenOrdersForVariant, getPrioritizedOrders } from "@/lib/domain/metrics";
import { detectAlerts } from "@/lib/domain/alerts";
import { createFallbackBrief } from "@/lib/domain/brief";
import { validateGroundedBrief } from "@/lib/ai/synthesis";

describe("multi-merchant metrics, priority, and brief",()=>{
  it("aggregates a unified queue across eight stores",()=>{const data=createDemoSnapshot();expect(data.merchants).toHaveLength(8);expect(data.stores).toHaveLength(8);expect(data.orders).toHaveLength(56);expect(new Set(data.orders.map(order=>order.storeId)).size).toBe(8);});
  it("calculates merchant and store filtering without leakage",()=>{const data=createDemoSnapshot();const merchantId=data.merchants[0].id;const storeId=data.stores[0].id;const merchantOrders=data.orders.filter(order=>order.merchantId===merchantId);const storeOrders=data.orders.filter(order=>order.storeId===storeId);expect(merchantOrders).toHaveLength(7);expect(storeOrders).toHaveLength(7);expect(merchantOrders.every(order=>order.storeId===storeId)).toBe(true);expect(storeOrders.every(order=>order.merchantId===merchantId)).toBe(true);});
  it("calculates open, ageing, and blocked workload",()=>{const metrics=calculateMetrics(createDemoSnapshot(),DEFAULT_THRESHOLDS);expect(metrics.totalOpenOrders).toBeGreaterThan(0);expect(metrics.olderThan24h).toBeGreaterThan(metrics.olderThan48h);expect(metrics.paymentBlockedOrders).toBeGreaterThan(0);});
  it("excludes cancelled and closed orders from open work",()=>{const data=createDemoSnapshot();const open=data.orders.find(order=>order.fulfillmentStatus!=="FULFILLED")!;const baseline=calculateMetrics(data,DEFAULT_THRESHOLDS).totalOpenOrders;open.cancelledAt=data.generatedAt;open.closed=true;expect(calculateMetrics(data,DEFAULT_THRESHOLDS).totalOpenOrders).toBe(baseline-1);expect(getPrioritizedOrders(data,DEFAULT_THRESHOLDS).some(item=>item.order.id===open.id)).toBe(false);});
  it("excludes cancelled and closed orders from inventory demand",()=>{const data=createDemoSnapshot();const variant=data.products.flatMap(product=>product.variants).find(candidate=>data.orders.some(order=>order.lineItems.some(item=>item.variantId===candidate.id)))!;const matching=data.orders.filter(order=>order.merchantId===variant.merchantId&&order.storeId===variant.storeId&&order.lineItems.some(item=>item.variantId===variant.id));expect(matching.length).toBeGreaterThanOrEqual(3);matching[0].cancelledAt=data.generatedAt;matching[1].closed=true;matching[2].fulfillmentStatus="FULFILLED";const affected=getOpenOrdersForVariant(data,variant.merchantId,variant.storeId,variant.id);expect(affected.some(order=>order.id===matching[0].id)).toBe(false);expect(affected.some(order=>order.id===matching[1].id)).toBe(false);expect(affected.some(order=>order.id===matching[2].id)).toBe(false);});
  it("calculates average age and oldest order per merchant",()=>{const backlogs=calculateMerchantBacklogs(createDemoSnapshot(),DEFAULT_THRESHOLDS);const northstar=backlogs.find(item=>item.merchantId==="mer_northstar")!;expect(northstar.averageAgeHours).toBeGreaterThan(0);expect(northstar.oldestOrderHours).toBe(79);});
  it("keeps the no-risk merchant clear",()=>{const backlog=calculateMerchantBacklogs(createDemoSnapshot(),DEFAULT_THRESHOLDS).find(item=>item.merchantId==="mer_alder")!;expect(backlog).toMatchObject({openOrders:0,riskLevel:"clear",oldestOrderHours:0});});
  it("scores inventory, age, payment, and service-level inputs deterministically",()=>{const data=createDemoSnapshot();const priority=calculateOrderPriority(data,data.orders.find(item=>item.id==="ord_1_1")!,DEFAULT_THRESHOLDS);expect(priority.score).toBeGreaterThanOrEqual(85);expect(priority.reasons).toContain("Available inventory is below the order quantity");expect(priority.reasons.some(reason=>reason.includes("service-level"))).toBe(true);});
  it("sorts unified work by operational priority",()=>{const queue=getPrioritizedOrders(createDemoSnapshot(),DEFAULT_THRESHOLDS);expect(queue.every((item,index)=>index===0||queue[index-1].priority.score>=item.priority.score)).toBe(true);});
  it("creates a deterministic cross-merchant brief",()=>{const data=createDemoSnapshot();const alerts=detectAlerts(data,DEFAULT_THRESHOLDS);const metrics=calculateMetrics(data,DEFAULT_THRESHOLDS);const first=createFallbackBrief(data,alerts,metrics);const second=createFallbackBrief(data,alerts,metrics);expect(first).toEqual(second);expect(first.summary).toContain("8 merchant");expect(first.priorities.every(item=>item.merchantName&&item.storeName)).toBe(true);});
  it("shows each underlying work item only once in the operations brief",()=>{const data=createDemoSnapshot();const alerts=detectAlerts(data,DEFAULT_THRESHOLDS);const metrics=calculateMetrics(data,DEFAULT_THRESHOLDS);const eligible=alerts.filter(alert=>["inventory_constraint","order_age_48","payment_blocked","partial_fulfillment","merchant_backlog"].includes(alert.issueType));const eligibleKeys=eligible.map(alert=>`${alert.recordType}:${alert.recordId}`);expect(new Set(eligibleKeys).size).toBeLessThan(eligibleKeys.length);const brief=createFallbackBrief(data,alerts,metrics);const selected=brief.priorities.map(priority=>alerts.find(alert=>alert.id===priority.alertId)!);const selectedKeys=selected.map(alert=>`${alert.recordType}:${alert.recordId}`);expect(new Set(selectedKeys).size).toBe(selectedKeys.length);for(const alert of selected){const strongest=Math.max(...eligible.filter(candidate=>candidate.recordType===alert.recordType&&candidate.recordId===alert.recordId).map(candidate=>candidate.priorityScore));expect(alert.priorityScore).toBe(strongest);}});
  it("accepts only the exact brief allowlist",()=>{const data=createDemoSnapshot();const alerts=detectAlerts(data,DEFAULT_THRESHOLDS);const metrics=calculateMetrics(data,DEFAULT_THRESHOLDS);const fallback=createFallbackBrief(data,alerts,metrics);const allowed=new Set(fallback.priorities.map(priority=>priority.alertId));const candidate={...fallback,generatedBy:"openai" as const};expect(validateGroundedBrief(candidate,fallback,allowed)).toBe(true);expect(validateGroundedBrief({...candidate,changeSummary:"Invented change"},fallback,allowed)).toBe(false);expect(validateGroundedBrief({...candidate,priorities:candidate.priorities.map((priority,index)=>index===0?{...priority,alertId:"not-allowed"}:priority)},fallback,allowed)).toBe(false);});
});
