import Link from "next/link";
import { ArrowRight, Code2, Gauge, HeartHandshake, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { CaseSection } from "@/components/case-section";
import { getStoreResult } from "@/lib/data/store";

export const dynamic="force-dynamic";
const metrics=["Time to identify the day’s highest-priority issues","Alerts judged useful by merchants","AI answers supported by cited records","Unsupported questions correctly declined","Merchant confidence in recommendations","False-positive alerts per review session"];

export default async function CaseStudyPage(){const result=await getStoreResult();const s=result.snapshot;return <AppShell source={s.source} storeName={s.shop.name} warning={result.liveError}><main className="mx-auto max-w-[1050px] px-4 py-6 sm:px-6 lg:px-8 lg:py-10">
  <div className="rounded-[26px] bg-[#1f2d26] px-6 py-10 text-white sm:px-10 sm:py-14"><p className="small-caps text-[9px] font-bold text-[#efc976]">Product case study · Independent portfolio work</p><h1 className="mt-5 max-w-[760px] text-[38px] font-bold leading-[1.02] tracking-[-.055em] sm:text-[54px]">From scattered store records to explainable daily priorities.</h1><p className="mt-6 max-w-[680px] text-[12px] leading-6 text-[#c2d0c7]">StoreOps Copilot explores how transparent operational rules and grounded AI can help Shopify merchants understand what needs attention—without automating irreversible actions.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/" className="inline-flex items-center gap-2 rounded-xl bg-[#efc976] px-4 py-2.5 text-[9px] font-bold text-[#263229]">Open the prototype <ArrowRight size={12}/></Link><Link href="/methodology" className="rounded-xl border border-white/15 px-4 py-2.5 text-[9px] font-bold">Review methodology</Link></div></div>
  <div className="grid gap-3 py-6 sm:grid-cols-3">{[[HeartHandshake,"Merchant problem","Prioritization, not more reporting"],[Gauge,"Narrow MVP","Three complete workflows"],[ShieldCheck,"Trust model","Facts → rules → reviewed action"]].map(([Icon,label,value])=>{const C=Icon as typeof HeartHandshake;return <div key={String(label)} className="rounded-2xl border border-[#dfe2dc] bg-[#fffefa] p-4"><C size={16} className="text-[#b75436]"/><p className="small-caps mt-4 text-[8px] font-bold text-[#8b948d]">{String(label)}</p><p className="mt-1 text-[11px] font-bold">{String(value)}</p></div>})}</div>
  <CaseSection number="01" title="Problem"><p>While helping a business evaluate its Shopify fulfilment operations, I observed how difficult it can be to identify what needs attention across orders, inventory, and customer activity. I independently built StoreOps Copilot to explore how Shopify data, transparent operational rules, and grounded AI could help merchants move from dashboards to decisions.</p><p>This is an independently built portfolio prototype. It is not a client-owned deliverable, production Shopify app, or Shopify-endorsed product.</p></CaseSection>
  <CaseSection number="02" title="Target user and discovery context"><p>The primary user is a small or mid-sized merchant, operations manager, or fulfilment lead who has access to operational data but limited time to reconcile several screens. The observed tension was not a lack of information; it was the work required to prioritize, explain, and act on it.</p><div className="rounded-xl bg-[#f0f3ee] p-4 text-[#46544a]">This framing comes from workflow observation and personal dogfooding—not completed merchant interviews or measured external validation.</div></CaseSection>
  <CaseSection number="03" title="Product hypothesis"><p>If operational store data is converted into transparent, explainable priorities, merchants can identify important issues faster than by manually reviewing multiple admin views and reports.</p><p>The riskiest assumptions are whether the default rules match real merchant operating models, whether evidence improves trust, and whether the recommended next steps feel helpful rather than prescriptive.</p></CaseSection>
  <CaseSection number="04" title="MVP scope and key workflows"><div className="grid gap-3 sm:grid-cols-3">{[["01","Overdue order","Find an ageing unfulfilled order, explain the 48-hour rule, inspect the source order, and suggest a review step."],["02","Inventory risk","Identify low or excess inventory using configurable thresholds and visible sales context."],["03","Ask Store","Map a natural-language question to a closed query, calculate outside the model, and cite visible records."]].map(([n,t,b])=><div key={n} className="rounded-xl border border-[#dde2db] bg-white p-4"><p className="font-mono text-[8px] text-[#9aa19b]">{n}</p><h3 className="mt-3 text-[11px] font-bold text-[#273129]">{t}</h3><p className="mt-2 text-[9px] leading-5">{b}</p></div>)}</div></CaseSection>
  <CaseSection number="05" title="Product decisions"><ul className="space-y-3">{["Demo-first: a reviewer gets the complete experience with no credentials.","Deterministic alert status: an LLM cannot create, rank, or change an operational fact.","Evidence before recommendation: every issue opens into source data, rule, threshold, and next step.","Read-only by design: recommendations stop before any Shopify write action.","No vector database: a small, structured snapshot is filtered by a typed query registry.","Live connection after the learning loop: Shopify infrastructure cannot delay the core product test."].map(item=><li key={item} className="flex gap-3"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#c95a36]"/>{item}</li>)}</ul></CaseSection>
  <CaseSection number="06" title="Technical and AI approach"><p>Next.js server routes retrieve and normalize either simulated records or a read-only Shopify Admin GraphQL snapshot. Typed domain functions calculate metrics, evaluate rules, assign severity, rank priorities, and produce source-derived claims. The OpenAI Responses API is an optional, schema-constrained selection layer over that allowlist.</p><div className="flex items-start gap-3 rounded-xl border border-[#d7e1d8] bg-[#f3f8f3] p-4"><Code2 size={16} className="mt-0.5 shrink-0 text-[#3f6d50]"/><p className="text-[10px] leading-5">The application validates every returned sentence, value, record, link, and ordering. Any API, schema, or content mismatch falls back to the deterministic renderer.</p></div></CaseSection>
  <CaseSection number="07" title="How I used AI coding tools"><p>I used AI tools to increase iteration speed while retaining responsibility for product judgment, technical validation, and quality. AI supported initial framing, architecture exploration, code generation, refactoring, test generation, documentation, debugging, and prototype iteration.</p><p>Human judgment remained essential for scoping the merchant problem, selecting deterministic rules, deciding what not to build, validating API fields, reviewing generated code, handling unsupported model output, dogfooding the experience, and setting the final quality bar.</p></CaseSection>
  <CaseSection number="08" title="Trade-offs, risks, and limitations"><p>I deferred public OAuth, multitenancy, background sync, webhooks, billing, forecasting, write actions, and App Store submission. Those capabilities add cost before validating the most important question: are explainable priorities genuinely useful to merchants?</p><p>Prototype rules do not know seasonality, margin, inbound purchase orders, product strategy, carrier events, or merchant-specific service levels. Live data is bounded and may be incomplete. Sending store data to a model would require stronger minimization, retention controls, consent, and vendor review in production.</p></CaseSection>
  <CaseSection number="09" title="Proposed success metrics"><div className="grid gap-2 sm:grid-cols-2">{metrics.map(metric=><div key={metric} className="rounded-xl border border-[#e1e4df] bg-white p-3 text-[10px] text-[#4e5a52]">{metric}</div>)}</div><p>These are proposed measures, not claimed results.</p></CaseSection>
  <CaseSection number="10" title="Next experiments and merchant validation"><ol className="space-y-3">{["Interview five merchants about the last three operational decisions that required several admin views.","Run a task-based test: identify today’s most important issue using current workflow versus the prototype.","Have merchants judge alert usefulness, threshold fit, false positives, and confidence in the recommendation.","Build a factuality eval set for supported, unsupported, and ambiguous questions.","Only then test saved thresholds, follow-up questions, and proactive briefs."].map((item,index)=><li key={item} className="flex gap-3"><span className="font-mono text-[9px] text-[#a65438]">0{index+1}</span>{item}</li>)}</ol></CaseSection>
  <CaseSection number="11" title="What I learned"><p>The best AI product decision was to give AI less authority. Once alert detection, severity, ranking, metrics, and evidence selection became deterministic, the conversational layer became easier to trust, test, and explain. The prototype is strongest when it helps a merchant inspect a decision—not when it tries to look autonomous.</p></CaseSection>
</main></AppShell>}
