import Link from "next/link";
import { ArrowRight, Code2, Gauge, HeartHandshake, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { CaseSection } from "@/components/case-section";
import { getStoreResult } from "@/lib/data/store";

export const dynamic="force-dynamic";
const proposedMetrics=["Time required to identify all orders awaiting action","Shopify account switches per operator per day","Time required to review merchant backlogs","Percentage of overdue orders identified correctly","Percentage of alerts judged useful","False-positive alert rate","Time from order readiness to fulfilment action","Orders processed within merchant service-level targets","Operator confidence in prioritization","AI answers supported by cited records","Unsupported questions correctly declined","Repeat operator usage"];

export default async function CaseStudyPage(){const result=await getStoreResult();const s=result.snapshot;return <AppShell source={s.source} storeName={s.provider.name} storeCount={s.stores.length} warning={result.liveError}><main className="mx-auto max-w-[1050px] px-4 py-6 sm:px-6 lg:px-8 lg:py-10"><div className="rounded-[26px] bg-[#1f2d26] px-6 py-10 text-white sm:px-10 sm:py-14"><p className="small-caps text-[9px] font-bold text-[#efc976]">Product case study · Independent portfolio work</p><h1 className="mt-5 max-w-[800px] text-[38px] font-bold leading-[1.02] tracking-[-.055em] sm:text-[54px]">One fulfilment queue across merchant-owned Shopify stores.</h1><p className="mt-6 max-w-[720px] text-[12px] leading-6 text-[#c2d0c7]">An independently built, AI-assisted multi-merchant fulfilment operations prototype inspired by real workflow discovery.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/orders" className="inline-flex items-center gap-2 rounded-xl bg-[#efc976] px-4 py-2.5 text-[9px] font-bold text-[#263229]">Open unified queue <ArrowRight size={12}/></Link><Link href="/methodology" className="rounded-xl border border-white/15 px-4 py-2.5 text-[9px] font-bold">Review methodology</Link></div></div><div className="grid gap-3 py-6 sm:grid-cols-3">{[[HeartHandshake,"Primary user","Third-party fulfilment operator"],[Gauge,"Focused MVP","Queue, backlogs, explainable priority"],[ShieldCheck,"Trust model","Same-store facts → rules → review"]].map(([Icon,label,value])=>{const C=Icon as typeof HeartHandshake;return <div key={String(label)} className="rounded-2xl border border-[#dfe2dc] bg-[#fffefa] p-4"><C size={16} className="text-[#b75436]"/><p className="small-caps mt-4 text-[8px] font-bold text-[#8b948d]">{String(label)}</p><p className="mt-1 text-[11px] font-bold">{String(value)}</p></div>})}</div>
  <CaseSection number="01" title="Discovery context"><p>While helping a third-party fulfilment operator examine its Shopify workflows, I observed that the team repeatedly switched between merchant-owned Shopify accounts to review orders and complete fulfilment on each merchant’s behalf. I mapped the workflow and independently built StoreOps Copilot to explore whether a unified, explainable operations queue could help fulfilment teams identify and prioritize work across merchants.</p><p>The operator managed approximately eight merchant Shopify accounts and performed approximately 24 recurring manual account and workflow checks per day. Those figures describe discovery context only; this prototype does not serve those merchants or process production orders.</p></CaseSection>
  <CaseSection number="02" title="User"><p>The primary user is a fulfilment operator or team lead working across client-owned Shopify stores—not a merchant managing one store. They need to protect merchant context while checking readiness, assigning work, and tracking exceptions.</p></CaseSection>
  <CaseSection number="03" title="Existing workflow"><p>Operators switched account context, reviewed orders store by store, checked payment and line items, judged fulfilment readiness, processed work on the merchant’s behalf, and tracked what remained. The repeated reconciliation—not access to raw data—was the core friction.</p></CaseSection>
  <CaseSection number="04" title="Core problem"><p>There was no cross-merchant answer to: “Across every merchant we support, what does the fulfilment team need to act on today?” Work could age while attention was divided across separate admin sessions.</p></CaseSection>
  <CaseSection number="05" title="Product hypothesis"><p>If fulfilment-ready orders, blocks, ageing, inventory constraints, and merchant backlogs are consolidated into one explainable queue, operators can identify the right work with less account switching and stronger context.</p><p>This remains a hypothesis. No external outcome or time-saving claim has been measured.</p></CaseSection>
  <CaseSection number="06" title="MVP definition"><p>The MVP includes an eight-store simulated dataset, unified order queue, merchant/store filters, merchant backlog view, order detail, deterministic exceptions and priority, a daily operations brief, and grounded cross-store questions. It remains read-only.</p></CaseSection>
  <CaseSection number="07" title="Why a unified queue"><p>The queue optimizes for actionable fulfilment work rather than total commerce reporting. Every row carries merchant, store, payment, fulfilment, age, items, priority, exceptions, and a next step. Operators can filter without losing ownership context.</p></CaseSection>
  <CaseSection number="08" title="Multi-merchant data model"><p>The domain makes the hierarchy explicit: fulfilment provider → merchant → Shopify store → order, customer, product, alert, and task. Customer value is calculated only inside one merchant/store boundary. The public demo represents an internal operator view; production would require strict tenant isolation and role-based access.</p></CaseSection>
  <CaseSection number="09" title="Prioritization logic"><p>Operational priority is a deterministic score using order age, payment confirmation, fulfilment state, partial fulfilment, order value, same-store customer value, merchant service-level target, backlog risk, inventory availability, and manual exception signals.</p><p>It is rule-based prioritization—not prediction, machine-learning risk, or autonomous decision-making.</p></CaseSection>
  <CaseSection number="10" title="AI approach"><p>Typed retrieval determines whether a question applies to one merchant, one store, or all stores. Domain functions select same-scope records and calculate facts first. The OpenAI Responses API may return only the exact source-derived answer; schema, sentence, value, ordering, link, merchant ID, store ID, and cited-record validation must pass.</p></CaseSection>
  <CaseSection number="11" title="Product and technical trade-offs"><ul className="space-y-3">{["Demo-first access instead of an onboarding dependency.","Structured filtering instead of a vector database.","Deterministic decisions before model synthesis.","One server adapter that can aggregate multiple connections, without building full OAuth or persistence.","Read-only review steps instead of fulfilment mutations.","Bounded pagination and snapshots instead of background synchronization."].map(item=><li key={item} className="flex gap-3"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#c95a36]"/>{item}</li>)}</ul></CaseSection>
  <CaseSection number="12" title="Privacy and tenant isolation"><p>No client data, real merchant data, or real customer information is present. Demo identities are synthetic. Tokens remain server-side and the public data route returns demo records only. A production version would require OAuth, encrypted per-store token storage, role-based access, audit logs, retention controls, merchant authorization, and LLM governance.</p></CaseSection>
  <CaseSection number="13" title="Dogfooding"><p>I tested cross-merchant workload review, merchant and store filters, 48-hour orders, payment blocks, partially fulfilled orders, no-risk merchants, cross-store questions, merchant-specific questions, invalid references, and deterministic fallback. These are personal product tests—not external user feedback.</p></CaseSection>
  <CaseSection number="14" title="Proposed success metrics"><div className="grid gap-2 sm:grid-cols-2">{proposedMetrics.map(metric=><div key={metric} className="rounded-xl border border-[#e1e4df] bg-white p-3 text-[10px] text-[#4e5a52]">{metric}</div>)}</div><p>All measures are proposed until a real operator validation session occurs.</p></CaseSection>
  <CaseSection number="15" title="Next validation steps"><ol className="space-y-3">{["Ask a fulfilment operator to reconstruct the last three cross-store decisions and account switches.","Run a task test: find every ready, blocked, and overdue order without explanation from the builder.","Compare the operator’s priority order with the rule score and inspect disagreements.","Review alert usefulness, false positives, merchant boundaries, and confidence in evidence.","Test whether the brief changes capacity allocation decisions before expanding the product."].map((item,index)=><li key={item} className="flex gap-3"><span className="font-mono text-[9px] text-[#a65438]">0{index+1}</span>{item}</li>)}</ol></CaseSection>
  <CaseSection number="16" title="What I learned"><p>The largest correction was product framing: the valuable unit of work is not one store’s health but an operator decision across many client stores. Making merchant and store identity mandatory throughout the data model improved the queue, rules, explanations, and AI safety at the same time.</p><div className="flex items-start gap-3 rounded-xl border border-[#d7e1d8] bg-[#f3f8f3] p-4"><Code2 size={16} className="mt-0.5 shrink-0 text-[#3f6d50]"/><p className="text-[10px] leading-5">I used AI coding tools throughout development for exploration, implementation, testing, debugging, and documentation while retaining responsibility for problem framing, scope, rule design, validation, and release quality.</p></div></CaseSection>
</main></AppShell>}
