import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { EmptyState } from "@/components/empty-state";
import { getStoreResult } from "@/lib/data/store";
import { ageLabel, formatDateTime, formatMoney, hoursBetween } from "@/lib/domain/format";
import { DEFAULT_THRESHOLDS } from "@/lib/domain/config";

export const dynamic = "force-dynamic";
export default async function OrdersPage() {
  const result=await getStoreResult(); const s=result.snapshot;
  return <AppShell source={s.source} storeName={s.shop.name} warning={result.liveError}><main className="mx-auto max-w-[1120px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><PageHeader eyebrow="Store records" title="Orders" description="Fulfilment status, age, value, and customer context. Alert state is calculated separately from these source records."/>{s.orders.length===0&&<div className="mt-6"><EmptyState title="No orders are available" body="The current data source returned no order records. Check live-store access or continue with demo mode."/></div>}<section className="mt-6 overflow-hidden rounded-[20px] border border-[#dfe2dc] bg-[#fffefa]"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><caption className="sr-only">Available store orders</caption><thead><tr className="border-b border-[#e5e8e3] bg-[#faf9f6] text-[8px] uppercase tracking-[.1em] text-[#7c867e]"><th className="px-5 py-3">Order</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Created</th><th className="px-4 py-3">Age</th><th className="px-4 py-3">Fulfilment</th><th className="px-4 py-3 text-right">Value</th><th className="px-5 py-3"><span className="sr-only">Open</span></th></tr></thead><tbody>{s.orders.map(order=>{const age=hoursBetween(s.generatedAt,order.createdAt);const overdue=order.financialStatus==="PAID"&&order.fulfillmentStatus!=="FULFILLED"&&age>DEFAULT_THRESHOLDS.overdueHours;return <tr key={order.id} className="border-b border-[#eceeea] last:border-0 hover:bg-[#fcfcf9]"><td className="px-5 py-4"><Link href={`/orders/${order.id}` as never} className="text-[11px] font-bold hover:text-[#b45032]">{order.name}</Link><p className="mt-0.5 text-[8px] text-[#929a93]">{order.lineItems.length} line item{order.lineItems.length===1?"":"s"}</p></td><td className="px-4 py-4 text-[10px]">{order.customerName}</td><td className="px-4 py-4 text-[9px] text-[#748078]">{formatDateTime(order.createdAt,s.shop.timezone)}</td><td className={`px-4 py-4 text-[9px] font-semibold ${overdue?"text-[#ad4a30]":"text-[#667269]"}`}>{ageLabel(age)}{overdue&&<span className="ml-2 rounded-full bg-[#fff0e8] px-2 py-1 text-[7px] uppercase">Overdue</span>}</td><td className="px-4 py-4 text-[9px]">{order.fulfillmentStatus.replaceAll("_"," ")}</td><td className="px-4 py-4 text-right text-[10px] font-bold">{formatMoney(order.total.amount,order.total.currencyCode)}</td><td className="px-5 py-4"><Link href={`/orders/${order.id}` as never} aria-label={`Open ${order.name}`}><ArrowUpRight size={13} className="text-[#9aa19b]"/></Link></td></tr>})}</tbody></table></div></section></main></AppShell>;
}
