import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { SourceBanner } from "@/components/source-banner";
import { getStoreResult } from "@/lib/data/store";
import { DEFAULT_THRESHOLDS } from "@/lib/domain/config";

export const dynamic="force-dynamic";
export default async function InventoryPage(){const result=await getStoreResult();const s=result.snapshot;const variants=s.products.flatMap(product=>product.variants);const merchantById=new Map(s.merchants.map(item=>[item.id,item]));const storeById=new Map(s.stores.map(item=>[item.id,item]));return <AppShell source={s.source} storeName={s.provider.name} storeCount={s.stores.length} warning={result.liveError}><main className="mx-auto max-w-[1180px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><PageHeader eyebrow="Across all merchant stores" title="Inventory constraints" description="Same-store availability is shown with merchant ownership preserved. Low-stock facts help operators spot orders that may not be ready to pick."/><div className="mt-6"><SourceBanner result={result}/></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{variants.map(variant=>{const low=variant.available<DEFAULT_THRESHOLDS.lowInventoryUnits;return <Link href={`/inventory/${variant.id}` as never} key={variant.id} className="group rounded-[18px] border border-[#dfe2dc] bg-[#fffefa] p-4 hover:border-[#b9c4bb]"><div className="flex items-start justify-between"><div><p className="text-[8px] font-bold uppercase tracking-[.08em] text-[#8a938b]">{merchantById.get(variant.merchantId)?.name} · {storeById.get(variant.storeId)?.name}</p><h2 className="mt-2 text-[12px] font-bold">{variant.productTitle}</h2><p className="mt-0.5 text-[9px] text-[#7d867f]">{variant.title} · {variant.sku}</p></div><ArrowUpRight size={13} className="text-[#9ca39d] group-hover:text-[#c95a36]"/></div><div className="mt-5 grid grid-cols-3 gap-2"><Stat value={variant.available} label="Available" attention={low}/><Stat value={variant.unitsSold7d} label="Sold · 7d"/><Stat value={variant.unitsSold30d} label="Sold · 30d"/></div>{low&&<p className="mt-3 text-[8px] font-bold uppercase tracking-[.08em] text-[#ad4a30]">Low inventory · review open orders</p>}</Link>})}</div></main></AppShell>}
function Stat({value,label,attention=false}:{value:number;label:string;attention?:boolean}){return <div><p className={`text-[20px] font-bold tracking-[-.04em] ${attention?"text-[#ad4a30]":""}`}>{value}</p><p className="text-[8px] text-[#848d86]">{label}</p></div>}
