import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { EmptyState } from "@/components/empty-state";
import { getStoreResult } from "@/lib/data/store";
import { DEFAULT_THRESHOLDS } from "@/lib/domain/config";

export const dynamic = "force-dynamic";
export default async function InventoryPage() {
  const result=await getStoreResult(); const s=result.snapshot; const variants=s.products.flatMap(product=>product.variants);
  return <AppShell source={s.source} storeName={s.shop.name} warning={result.liveError}><main className="mx-auto max-w-[1120px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><PageHeader eyebrow="Store records" title="Inventory" description={`Prototype defaults: low stock below ${DEFAULT_THRESHOLDS.lowInventoryUnits} units; excess inventory at ${DEFAULT_THRESHOLDS.excessInventoryUnits}+ units with ${DEFAULT_THRESHOLDS.lowVelocityUnits30d} or fewer 30-day sales.`}/>{variants.length===0&&<div className="mt-6"><EmptyState title="No variants are available" body="The current data source returned no product variants. Check product access or continue with demo mode."/></div>}<div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{variants.map(variant=>{const low=variant.available<DEFAULT_THRESHOLDS.lowInventoryUnits;const excess=variant.available>=DEFAULT_THRESHOLDS.excessInventoryUnits&&variant.unitsSold30d<=DEFAULT_THRESHOLDS.lowVelocityUnits30d;return <Link href={`/inventory/${variant.id}` as never} key={variant.id} className="group rounded-[18px] border border-[#dfe2dc] bg-[#fffefa] p-4 hover:border-[#b9c4bb]"><div className="flex items-start justify-between"><div><p className="text-[8px] font-bold uppercase tracking-[.08em] text-[#8a938b]">{variant.sku}</p><h2 className="mt-1 text-[12px] font-bold">{variant.productTitle}</h2><p className="mt-0.5 text-[9px] text-[#7d867f]">{variant.title}</p></div><ArrowUpRight size={13} className="text-[#9ca39d] group-hover:text-[#c95a36]"/></div><div className="mt-5 grid grid-cols-3 gap-2"><div><p className={`text-[20px] font-bold tracking-[-.04em] ${low?"text-[#ad4a30]":excess?"text-[#996222]":""}`}>{variant.available}</p><p className="text-[8px] text-[#848d86]">Available</p></div><div><p className="text-[20px] font-bold tracking-[-.04em]">{variant.unitsSold7d}</p><p className="text-[8px] text-[#848d86]">Sold · 7d</p></div><div><p className="text-[20px] font-bold tracking-[-.04em]">{variant.unitsSold30d}</p><p className="text-[8px] text-[#848d86]">Sold · 30d</p></div></div><div className="mt-4 h-1 overflow-hidden rounded-full bg-[#ecefe9]"><div className={`h-full rounded-full ${low?"bg-[#c95a36]":excess?"bg-[#d19a47]":"bg-[#5e8c70]"}`} style={{width:`${Math.min(100,Math.max(4,variant.available/1.5))}%`}}/></div>{(low||excess)&&<p className={`mt-3 text-[8px] font-bold uppercase tracking-[.08em] ${low?"text-[#ad4a30]":"text-[#936122]"}`}>{low?"Low inventory signal":"Excess inventory signal"}</p>}</Link>})}</div></main></AppShell>;
}
