import { AlertTriangle, Bot, Calculator, Database, FlaskConical, LockKeyhole, ShieldCheck } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { getStoreResult } from "@/lib/data/store";
import { DEFAULT_THRESHOLDS } from "@/lib/domain/config";

export const dynamic="force-dynamic";
const layers=[
  {icon:Database,title:"Store records",body:"Orders, customers, products, variants, inventory quantities, fulfilment state, and refunds are normalized server-side."},
  {icon:Calculator,title:"Deterministic findings",body:"Metrics, thresholds, alert state, severity, and priority are calculated in typed domain functions—not by a language model."},
  {icon:Bot,title:"Optional constrained AI",body:"The model may return only a source-derived answer from the allowlist. Any changed sentence, value, record, or link is rejected."},
];
export default async function MethodologyPage(){const result=await getStoreResult();const s=result.snapshot;return <AppShell source={s.source} storeName={s.shop.name} warning={result.liveError}><main className="mx-auto max-w-[980px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><PageHeader eyebrow="Responsible AI product judgment" title="How StoreOps Copilot works" description="A clear boundary between source data, rule-based findings, and optional model output makes every result easier to inspect and challenge."/>
  <section className="mt-8 grid gap-3 sm:grid-cols-3">{layers.map((layer,index)=><div key={layer.title} className="rounded-[18px] border border-[#dfe2dc] bg-[#fffefa] p-5"><div className="flex items-center justify-between"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#edf1ec] text-[#425d4c]"><layer.icon size={16}/></span><span className="font-mono text-[8px] text-[#a0a7a1]">0{index+1}</span></div><h2 className="mt-6 text-[13px] font-bold">{layer.title}</h2><p className="mt-2 text-[10px] leading-5 text-[#68736b]">{layer.body}</p></div>)}</section>
  <section className="mt-8 rounded-[22px] border border-[#dfe2dc] bg-[#fffefa] p-5 sm:p-7"><p className="small-caps text-[8px] font-bold text-[#7e8880]">Operational rulebook · prototype defaults</p><div className="mt-5 divide-y divide-[#e7e9e5]">{[["Overdue order",`Paid and not fulfilled for more than ${DEFAULT_THRESHOLDS.overdueHours} hours`],["Low inventory",`Available inventory below ${DEFAULT_THRESHOLDS.lowInventoryUnits} units`],["Excess inventory",`${DEFAULT_THRESHOLDS.excessInventoryUnits}+ available and ≤${DEFAULT_THRESHOLDS.lowVelocityUnits30d} sold in 30 days`],["Customer risk",`${new Intl.NumberFormat("en-CA",{style:"currency",currency:s.shop.currencyCode,maximumFractionDigits:0}).format(DEFAULT_THRESHOLDS.highValueCustomerAmount)} lifetime value plus an overdue order`],["Refund activity",`${DEFAULT_THRESHOLDS.refundCountThreshold}+ refunds in ${DEFAULT_THRESHOLDS.refundWindowDays} days and above the prior period`]].map(([rule,threshold])=><div key={rule} className="grid gap-1 py-4 sm:grid-cols-[180px_1fr]"><p className="text-[10px] font-bold">{rule}</p><p className="text-[10px] text-[#6d7770]">{threshold}</p></div>)}</div></section>
  <section className="mt-8 grid gap-4 sm:grid-cols-2"><TrustCard icon={ShieldCheck} title="Grounding safeguards" items={["Closed, typed question registry","Relevant records selected before model call","Metrics calculated outside the model","Structured output validation","Evidence IDs checked against an allowlist","Deterministic fallback on any failure"]}/><TrustCard icon={AlertTriangle} title="Unsupported questions" items={["No unrestricted SQL or GraphQL generation","No causal claims without evidence","No forecasting or stockout prediction","No write or automation requests","Clear ‘not enough information’ response","Examples of answerable questions"]}/><TrustCard icon={FlaskConical} title="Demo versus live data" items={["Demo mode is the default","Every demo identity is synthetic","Live mode requires server credentials","A persistent mode label remains visible","Live failure falls back with a warning","No secrets enter browser bundles"]}/><TrustCard icon={LockKeyhole} title="Why no automated actions" items={["Merchant context may be missing","Recommendations may be wrong","Order edits can be irreversible","Human review preserves control","Read-only scopes minimize exposure","Production safeguards are out of scope"]}/></section>
  <section className="mt-8 rounded-[20px] bg-[#26362d] p-6 text-white"><p className="small-caps text-[8px] font-bold text-[#e9c875]">Known limitations</p><p className="mt-3 max-w-[760px] text-[10px] leading-5 text-[#c5d2c9]">This prototype does not understand margin, seasonality, inbound stock, carrier events, product strategy, or every Shopify data edge case. Live history is capped. It is not production-ready. A production design would need stronger data minimization, retention controls, tenant isolation, model evals, observability, and merchant-configured thresholds.</p></section>
</main></AppShell>}

function TrustCard({icon:Icon,title,items}:{icon:typeof ShieldCheck;title:string;items:string[]}){return <section className="rounded-[18px] border border-[#dfe2dc] bg-[#fffefa] p-5"><div className="flex items-center gap-2"><Icon size={15} className="text-[#a95337]"/><h2 className="text-[12px] font-bold">{title}</h2></div><ul className="mt-4 space-y-2">{items.map(item=><li key={item} className="flex gap-2 text-[9px] leading-4 text-[#6c766f]"><span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-[#8fa094]"/>{item}</li>)}</ul></section>}
