import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/page-header";
import { SourceBanner } from "@/components/source-banner";
import { getStoreResult } from "@/lib/data/store";
import { DEFAULT_THRESHOLDS } from "@/lib/domain/config";
import { calculateMerchantBacklogs } from "@/lib/domain/metrics";
import { ageLabel } from "@/lib/domain/format";

export const dynamic="force-dynamic";
export default async function MerchantsPage(){const result=await getStoreResult();const s=result.snapshot;const backlogs=calculateMerchantBacklogs(s,DEFAULT_THRESHOLDS);const storeById=new Map(s.stores.map(store=>[store.id,store]));return <AppShell source={s.source} storeName={s.provider.name} storeCount={s.stores.length} warning={result.liveError}><main className="mx-auto max-w-[1180px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><PageHeader eyebrow="Client portfolio" title="Merchant backlogs" description="Compare workload, ageing, payment blocks, service levels, and operational risk without losing the boundary between merchant-owned stores."/><div className="mt-6"><SourceBanner result={result}/></div><div className="mt-6 grid gap-3 md:grid-cols-2">{backlogs.map(backlog=>{const merchant=s.merchants.find(item=>item.id===backlog.merchantId)!;const store=storeById.get(backlog.storeId)!;return <Link key={merchant.id} href={`/merchants/${merchant.id}` as never} className="group rounded-[20px] border border-[#dfe2dc] bg-[#fffefa] p-5 hover:border-[#b8c4ba]"><div className="flex items-start justify-between"><div><p className="text-[8px] font-bold uppercase tracking-[.08em] text-[#8a938b]">{store.name}</p><h2 className="mt-1 text-[15px] font-bold">{merchant.name}</h2><p className="mt-1 text-[9px] text-[#7d867f]">Service-level target · {merchant.serviceLevelTargetHours}h</p></div><div className="flex items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[8px] font-bold uppercase ${backlog.riskLevel==="elevated"?"bg-[#fee8e1] text-[#a7442d]":backlog.riskLevel==="watch"?"bg-[#fff0de] text-[#98601e]":"bg-[#e7f0e8] text-[#3e684b]"}`}>{backlog.riskLevel}</span><ArrowUpRight size={13} className="text-[#99a19a] group-hover:text-[#c95a36]"/></div></div><div className="mt-5 grid grid-cols-4 gap-3"><Stat label="Open" value={backlog.openOrders}/><Stat label="Paid" value={backlog.paidUnfulfilled}/><Stat label=">48h" value={backlog.olderThan48h}/><Stat label="Blocked" value={backlog.paymentBlocked}/></div><div className="mt-4 flex items-center justify-between border-t border-[#e8ebe6] pt-4 text-[9px] text-[#69746c]"><span>Oldest · {ageLabel(backlog.oldestOrderHours)}</span><span className={backlog.backlogChange>0?"font-bold text-[#a95337]":""}>{backlog.backlogChange>=0?"+":""}{backlog.backlogChange} vs prior</span></div></Link>})}</div></main></AppShell>}

function Stat({label,value}:{label:string;value:number}){return <div><p className="text-[20px] font-bold tracking-[-.04em]">{value}</p><p className="text-[8px] text-[#858e87]">{label}</p></div>}
